name = "variational-principle"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["VariationalPrinciple"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "VariationalPrinciple"
